[package]
name = "prisma-query"
version = "0.1.0"
authors = [
    "Julius de Bruijn <bruijn@prisma.io>",
    "Dominic Petrick <petrick@prisma.io>",
    "Katharina Fey <kookie@spacekookie.de>"
]
edition = "2018"

[features]
default = ["rusqlite", "json"]
sqlite3 = ["sqlite"]
json = ["serde_json"]

[dependencies]
sqlite = { version = "0.24", optional = true }
rusqlite = { version = "0.16", optional = true }
serde_json = { version = "1.0", optional = true }