[package]
name = "prisma-query"
version = "0.1.0"
authors = [
    "Julius de Bruijn <bruijn@prisma.io>",
    "Dominic Petrick <petrick@prisma.io>",
    "Katharina Fey <kookie@spacekookie.de>"
]
edition = "2018"

[features]
default = ["rusqlite-client", "json-1", "postgresql-0_16", "uuid-0_7", "chrono-0_4", "mysql_sync"]
rusqlite-client = ["rusqlite", "r2d2_sqlite", "r2d2", "libsqlite3-sys"]
sqlite3 = ["sqlite", "r2d2", "r2d2_sqlite"]
json-1 = ["serde_json"]
postgresql-0_16 = ["postgres", "rust_decimal", "r2d2"]
uuid-0_7 = ["uuid"]
chrono-0_4 = ["chrono"]
mysql_sync = ["mysql", "r2d2"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
rust_decimal = { git = "https://github.com/pimeys/rust-decimal.git", optional = true, features = ["postgres"] }
sqlite = { version = "0.24", optional = true }
rusqlite = { git = "https://github.com/pimeys/rusqlite", features = ["chrono"], optional = true }
serde_json = { version = "1.0", optional = true }
uuid = { version = "0.7", optional = true }
chrono = { version = "0.4", optional = true }
postgres = { version = "0.16.0-rc.1", optional = true, features = ["with-serde_json-1", "with-uuid-0_7", "with-chrono-0_4"]}
mysql = { version = "*", optional = true }
r2d2 = {  version = "0.8", optional = true }
r2d2_sqlite = { git = "https://github.com/pimeys/r2d2-sqlite", optional = true }
libsqlite3-sys = { git = "https://github.com/pimeys/rusqlite", optional = true }
