[package]
name = "prisma-query"
version = "0.1.0"
authors = [
    "Julius de Bruijn <bruijn@prisma.io>",
    "Dominic Petrick <petrick@prisma.io>",
    "Katharina Fey <kookie@spacekookie.de>",
    "Emanuel Jöbstl <emanuel.joebstl@gmail.com>"
]
edition = "2018"
readme  = "README.md"
license = "Apache-2.0"
description = "An abstraction layer for SQL databases."
repository  = "https://github.com/prisma/prisma-query/"
homepage    = "https://github.com/prisma/prisma-query/"
keywords    = ["mysql", "postgresql", "sqlite", "sql"]
documentation = "https://docs.rs/prisma-query/"

[features]
default = ["rusqlite-client", "json-1", "postgresql-0_16", "uuid-0_7", "chrono-0_4", "mysql_sync" ]
rusqlite-client = ["rusqlite", "r2d2_sqlite", "r2d2", "libsqlite3-sys"]
sqlite3 = ["sqlite", "r2d2", "r2d2_sqlite"]
json-1 = ["serde_json"]
postgresql-0_16 = ["postgres", "rust_decimal", "r2d2", "r2d2_postgres", "native-tls", "tokio-postgres", "tokio-postgres-native-tls", "array"]
uuid-0_7 = ["uuid"]
chrono-0_4 = ["chrono"]
mysql_sync = ["mysql", "r2d2", "r2d2_mysql"]
array = []

[dependencies]
failure = "0.1"
failure_derive = "0.1"
rust_decimal = { git = "https://github.com/pimeys/rust-decimal.git", optional = true, features = ["postgres"] }
sqlite = { version = "0.24", optional = true }
libsqlite3-sys = { version = "0.15", optional = true }
rusqlite = { version = "0.19", features = ["chrono"], optional = true }
serde_json = { version = "1.0", optional = true }
uuid = { version = "0.7", optional = true }
chrono = { version = "0.4", optional = true }
url = "1.7"

r2d2 = {  version = "0.8", optional = true }

r2d2_sqlite = { version = "0.11", optional = true }

postgres = { version = "0.16.0-rc.1", features = ["with-serde_json-1", "with-chrono-0_4", "with-uuid-0_7"], optional = true}
r2d2_postgres = { version = "0.15.0-rc.1", optional = true }
native-tls = { version = "0.2", optional = true }
tokio-postgres-native-tls = { version = "0.1.0-rc.1", optional = true }
tokio-postgres = { version = "0.4.0-rc.2", optional = true }

mysql = { version = "*", optional = true }
r2d2_mysql= { version = "*", optional = true }
